-- Pruebas de Poblar OK - Ciclo 2

-- 50 Tarifas
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (1, 'Concepto_1', 1000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (2, 'Concepto_2', 2000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (3, 'Concepto_3', 3000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (4, 'Concepto_4', 4000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (5, 'Concepto_5', 5000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (6, 'Concepto_6', 6000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (7, 'Concepto_7', 7000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (8, 'Concepto_8', 8000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (9, 'Concepto_9', 9000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (10, 'Concepto_10', 10000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (11, 'Concepto_11', 11000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (12, 'Concepto_12', 12000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (13, 'Concepto_13', 13000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (14, 'Concepto_14', 14000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (15, 'Concepto_15', 15000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (16, 'Concepto_16', 16000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (17, 'Concepto_17', 17000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (18, 'Concepto_18', 18000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (19, 'Concepto_19', 19000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (20, 'Concepto_20', 20000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (21, 'Concepto_21', 21000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (22, 'Concepto_22', 22000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (23, 'Concepto_23', 23000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (24, 'Concepto_24', 24000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (25, 'Concepto_25', 25000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (26, 'Concepto_26', 26000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (27, 'Concepto_27', 27000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (28, 'Concepto_28', 28000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (29, 'Concepto_29', 29000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (30, 'Concepto_30', 30000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (31, 'Concepto_31', 31000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (32, 'Concepto_32', 32000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (33, 'Concepto_33', 33000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (34, 'Concepto_34', 34000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (35, 'Concepto_35', 35000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (36, 'Concepto_36', 36000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (37, 'Concepto_37', 37000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (38, 'Concepto_38', 38000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (39, 'Concepto_39', 39000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (40, 'Concepto_40', 40000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (41, 'Concepto_41', 41000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (42, 'Concepto_42', 42000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (43, 'Concepto_43', 43000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (44, 'Concepto_44', 44000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (45, 'Concepto_45', 45000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (46, 'Concepto_46', 46000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (47, 'Concepto_47', 47000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (48, 'Concepto_48', 48000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (49, 'Concepto_49', 49000);
INSERT INTO Tarifa (Id_Tarifa, Concepto, Valor) VALUES (50, 'Concepto_50', 50000);

-- 50 Nominas
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (1, 2, 100, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (2, 3, 101, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (3, 4, 102, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (4, 1, 103, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (5, 1, 104, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (6, 2, 105, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (7, 3, 106, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (8, 4, 107, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (9, 1, 200, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (10, 1, 201, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (11, 2, 202, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (12, 3, 203, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (13, 4, 300, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (14, 1, 301, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (15, 1, 302, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (16, 2, 303, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (17, 3, 100, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (18, 4, 101, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (19, 1, 102, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (20, 1, 103, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (21, 2, 104, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (22, 3, 105, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (23, 4, 106, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (24, 1, 107, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (25, 1, 200, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (26, 2, 201, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (27, 3, 202, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (28, 4, 203, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (29, 1, 300, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (30, 1, 301, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (31, 2, 302, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (32, 3, 303, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (33, 4, 100, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (34, 1, 101, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (35, 1, 102, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (36, 2, 103, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (37, 3, 104, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (38, 4, 105, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (39, 1, 106, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (40, 1, 107, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (41, 2, 200, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (42, 3, 201, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (43, 4, 202, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (44, 1, 203, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (45, 1, 300, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (46, 2, 301, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (47, 3, 302, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (48, 4, 303, 'SI');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (49, 1, 100, 'NO');
INSERT INTO Nomina (Id_Nomina, Id_Partido, Id_Jugador, Titular) VALUES (50, 1, 101, 'SI');

-- 50 Incidencias
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (1, 2, 4, 100, 1, 'Amarilla');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (2, 3, 13, 101, 2, 'Roja');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (3, 4, 3, 102, 3, 'Falta');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (4, 1, 4, 103, 4, 'Lesion');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (5, 1, 13, 104, 5, 'Gol');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (6, 2, 3, 105, 6, 'Amarilla');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (7, 3, 4, 106, 7, 'Roja');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (8, 4, 13, 107, 8, 'Falta');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (9, 1, 3, 200, 9, 'Lesion');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (10, 1, 4, 201, 10, 'Gol');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (11, 2, 13, 202, 11, 'Amarilla');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (12, 3, 3, 203, 12, 'Roja');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (13, 4, 4, 300, 13, 'Falta');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (14, 1, 13, 301, 14, 'Lesion');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (15, 1, 3, 302, 15, 'Gol');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (16, 2, 4, 303, 16, 'Amarilla');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (17, 3, 13, 100, 17, 'Roja');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (18, 4, 3, 101, 18, 'Falta');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (19, 1, 4, 102, 19, 'Lesion');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (20, 1, 13, 103, 20, 'Gol');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (21, 2, 3, 104, 21, 'Amarilla');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (22, 3, 4, 105, 22, 'Roja');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (23, 4, 13, 106, 23, 'Falta');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (24, 1, 3, 107, 24, 'Lesion');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (25, 1, 4, 200, 25, 'Gol');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (26, 2, 13, 201, 26, 'Amarilla');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (27, 3, 3, 202, 27, 'Roja');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (28, 4, 4, 203, 28, 'Falta');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (29, 1, 13, 300, 29, 'Lesion');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (30, 1, 3, 301, 30, 'Gol');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (31, 2, 4, 302, 31, 'Amarilla');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (32, 3, 13, 303, 32, 'Roja');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (33, 4, 3, 100, 33, 'Falta');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (34, 1, 4, 101, 34, 'Lesion');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (35, 1, 13, 102, 35, 'Gol');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (36, 2, 3, 103, 36, 'Amarilla');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (37, 3, 4, 104, 37, 'Roja');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (38, 4, 13, 105, 38, 'Falta');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (39, 1, 3, 106, 39, 'Lesion');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (40, 1, 4, 107, 40, 'Gol');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (41, 2, 13, 200, 41, 'Amarilla');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (42, 3, 3, 201, 42, 'Roja');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (43, 4, 4, 202, 43, 'Falta');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (44, 1, 13, 203, 44, 'Lesion');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (45, 1, 3, 300, 45, 'Gol');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (46, 2, 4, 301, 46, 'Amarilla');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (47, 3, 13, 302, 47, 'Roja');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (48, 4, 3, 303, 48, 'Falta');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (49, 1, 4, 100, 49, 'Lesion');
INSERT INTO Incidencia (Id_Incidencia, Id_Partido, Id_Arbitro, Id_Jugador, Minuto, Tipo) VALUES (50, 1, 13, 101, 50, 'Gol');

-- 50 Resoluciones
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (1, 1, 1, 1000, 'Resolucion automatica 1');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (2, 2, 2, 2000, 'Resolucion automatica 2');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (3, 3, 0, 3000, 'Resolucion automatica 3');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (4, 4, 1, 4000, 'Resolucion automatica 4');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (5, 5, 2, 5000, 'Resolucion automatica 5');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (6, 6, 0, 6000, 'Resolucion automatica 6');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (7, 7, 1, 7000, 'Resolucion automatica 7');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (8, 8, 2, 8000, 'Resolucion automatica 8');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (9, 9, 0, 9000, 'Resolucion automatica 9');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (10, 10, 1, 10000, 'Resolucion automatica 10');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (11, 11, 2, 11000, 'Resolucion automatica 11');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (12, 12, 0, 12000, 'Resolucion automatica 12');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (13, 13, 1, 13000, 'Resolucion automatica 13');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (14, 14, 2, 14000, 'Resolucion automatica 14');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (15, 15, 0, 15000, 'Resolucion automatica 15');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (16, 16, 1, 16000, 'Resolucion automatica 16');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (17, 17, 2, 17000, 'Resolucion automatica 17');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (18, 18, 0, 18000, 'Resolucion automatica 18');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (19, 19, 1, 19000, 'Resolucion automatica 19');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (20, 20, 2, 20000, 'Resolucion automatica 20');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (21, 21, 0, 21000, 'Resolucion automatica 21');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (22, 22, 1, 22000, 'Resolucion automatica 22');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (23, 23, 2, 23000, 'Resolucion automatica 23');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (24, 24, 0, 24000, 'Resolucion automatica 24');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (25, 25, 1, 25000, 'Resolucion automatica 25');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (26, 26, 2, 26000, 'Resolucion automatica 26');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (27, 27, 0, 27000, 'Resolucion automatica 27');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (28, 28, 1, 28000, 'Resolucion automatica 28');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (29, 29, 2, 29000, 'Resolucion automatica 29');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (30, 30, 0, 30000, 'Resolucion automatica 30');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (31, 31, 1, 31000, 'Resolucion automatica 31');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (32, 32, 2, 32000, 'Resolucion automatica 32');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (33, 33, 0, 33000, 'Resolucion automatica 33');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (34, 34, 1, 34000, 'Resolucion automatica 34');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (35, 35, 2, 35000, 'Resolucion automatica 35');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (36, 36, 0, 36000, 'Resolucion automatica 36');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (37, 37, 1, 37000, 'Resolucion automatica 37');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (38, 38, 2, 38000, 'Resolucion automatica 38');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (39, 39, 0, 39000, 'Resolucion automatica 39');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (40, 40, 1, 40000, 'Resolucion automatica 40');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (41, 41, 2, 41000, 'Resolucion automatica 41');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (42, 42, 0, 42000, 'Resolucion automatica 42');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (43, 43, 1, 43000, 'Resolucion automatica 43');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (44, 44, 2, 44000, 'Resolucion automatica 44');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (45, 45, 0, 45000, 'Resolucion automatica 45');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (46, 46, 1, 46000, 'Resolucion automatica 46');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (47, 47, 2, 47000, 'Resolucion automatica 47');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (48, 48, 0, 48000, 'Resolucion automatica 48');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (49, 49, 1, 49000, 'Resolucion automatica 49');
INSERT INTO Resolucion (Id_Resolucion, Id_Incidencia, Fechas_Suspension, Multa_Monto, Descripcion) VALUES (50, 50, 2, 50000, 'Resolucion automatica 50');

-- 50 Estadisticas Jugador
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (1, 1, 1, 1, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (2, 2, 1, 2, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (3, 3, 1, 0, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (4, 4, 1, 1, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (5, 5, 1, 2, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (6, 6, 1, 0, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (7, 7, 1, 1, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (8, 8, 1, 2, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (9, 9, 1, 0, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (10, 10, 1, 1, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (11, 11, 1, 2, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (12, 12, 1, 0, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (13, 13, 1, 1, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (14, 14, 1, 2, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (15, 15, 1, 0, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (16, 16, 1, 1, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (17, 17, 1, 2, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (18, 18, 1, 0, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (19, 19, 1, 1, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (20, 20, 1, 2, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (21, 21, 1, 0, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (22, 22, 1, 1, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (23, 23, 1, 2, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (24, 24, 1, 0, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (25, 25, 1, 1, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (26, 26, 1, 2, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (27, 27, 1, 0, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (28, 28, 1, 1, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (29, 29, 1, 2, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (30, 30, 1, 0, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (31, 31, 1, 1, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (32, 32, 1, 2, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (33, 33, 1, 0, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (34, 34, 1, 1, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (35, 35, 1, 2, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (36, 36, 1, 0, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (37, 37, 1, 1, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (38, 38, 1, 2, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (39, 39, 1, 0, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (40, 40, 1, 1, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (41, 41, 1, 2, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (42, 42, 1, 0, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (43, 43, 1, 1, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (44, 44, 1, 2, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (45, 45, 1, 0, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (46, 46, 1, 1, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (47, 47, 1, 2, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (48, 48, 1, 0, 0, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (49, 49, 1, 1, 1, 0);
INSERT INTO Estadistica_Jugador (Id_Estadistica, Id_Jugador, Id_Torneo, Goles, Tarjetas_Amarillas, Tarjetas_Rojas) VALUES (50, 50, 1, 2, 0, 0);

-- 50 Facturas
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (1, NULL, 1, 1, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 1000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (2, NULL, 2, 2, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 2000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (3, NULL, 3, 3, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 3000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (4, NULL, 4, 4, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 4000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (5, NULL, 5, 5, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 5000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (6, NULL, 6, 6, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 6000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (7, NULL, 7, 7, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 7000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (8, NULL, 8, 8, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 8000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (9, NULL, 9, 9, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 9000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (10, NULL, 10, 10, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 10000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (11, NULL, 11, 11, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 11000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (12, NULL, 12, 12, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 12000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (13, NULL, 13, 13, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 13000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (14, NULL, 14, 14, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 14000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (15, NULL, 15, 15, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 15000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (16, NULL, 16, 16, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 16000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (17, NULL, 17, 17, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 17000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (18, NULL, 18, 18, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 18000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (19, NULL, 19, 19, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 19000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (20, NULL, 20, 20, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 20000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (21, NULL, 21, 21, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 21000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (22, NULL, 22, 22, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 22000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (23, NULL, 23, 23, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 23000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (24, NULL, 24, 24, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 24000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (25, NULL, 25, 25, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 25000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (26, NULL, 26, 26, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 26000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (27, NULL, 27, 27, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 27000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (28, NULL, 28, 28, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 28000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (29, NULL, 29, 29, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 29000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (30, NULL, 30, 30, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 30000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (31, NULL, 31, 31, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 31000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (32, NULL, 32, 32, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 32000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (33, NULL, 33, 33, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 33000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (34, NULL, 34, 34, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 34000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (35, NULL, 35, 35, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 35000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (36, NULL, 36, 36, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 36000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (37, NULL, 37, 37, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 37000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (38, NULL, 38, 38, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 38000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (39, NULL, 39, 39, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 39000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (40, NULL, 40, 40, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 40000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (41, NULL, 41, 41, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 41000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (42, NULL, 42, 42, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 42000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (43, NULL, 43, 43, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 43000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (44, NULL, 44, 44, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 44000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (45, NULL, 45, 45, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 45000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (46, NULL, 46, 46, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 46000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (47, NULL, 47, 47, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 47000, 'Anulada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (48, NULL, 48, 48, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 48000, 'Pagada');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (49, NULL, 49, 49, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 49000, 'Pendiente');
INSERT INTO Factura (Id_Factura, Id_Inscripcion, Id_Resolucion, Id_Tarifa, Fecha_Emision, Total, Estado) VALUES (50, NULL, 50, 50, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 50000, 'Anulada');

-- 50 Pagos
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (1, 1, 2, 1000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (2, 2, 3, 2000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (3, 3, 4, 3000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (4, 4, 5, 4000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (5, 5, 1, 5000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (6, 6, 2, 6000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (7, 7, 3, 7000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (8, 8, 4, 8000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (9, 9, 5, 9000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (10, 10, 1, 10000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (11, 11, 2, 11000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (12, 12, 3, 12000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (13, 13, 4, 13000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (14, 14, 5, 14000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (15, 15, 1, 15000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (16, 16, 2, 16000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (17, 17, 3, 17000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (18, 18, 4, 18000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (19, 19, 5, 19000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (20, 20, 1, 20000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (21, 21, 2, 21000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (22, 22, 3, 22000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (23, 23, 4, 23000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (24, 24, 5, 24000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (25, 25, 1, 25000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (26, 26, 2, 26000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (27, 27, 3, 27000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (28, 28, 4, 28000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (29, 29, 5, 29000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (30, 30, 1, 30000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (31, 31, 2, 31000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (32, 32, 3, 32000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (33, 33, 4, 33000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (34, 34, 5, 34000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (35, 35, 1, 35000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (36, 36, 2, 36000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (37, 37, 3, 37000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (38, 38, 4, 38000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (39, 39, 5, 39000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (40, 40, 1, 40000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (41, 41, 2, 41000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (42, 42, 3, 42000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (43, 43, 4, 43000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (44, 44, 5, 44000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (45, 45, 1, 45000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (46, 46, 2, 46000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (47, 47, 3, 47000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (48, 48, 4, 48000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (49, 49, 5, 49000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
INSERT INTO Pago (Id_Pago, Id_Factura, Id_Representante, Monto, Fecha_Pago) VALUES (50, 50, 1, 50000, TO_DATE('2024-01-02', 'YYYY-MM-DD'));
