-- ========================================================================
-- ELIMINACION DE DISPARADORES Y SECUENCIAS - CICLO 2
-- ========================================================================

-- Eliminar Triggers de Logica de Negocio
DROP TRIGGER TRG_ADICIONAR_FACTURA;
DROP TRIGGER TRG_ELIMINAR_FACTURA;
DROP TRIGGER TRG_ADICIONAR_PAGO;
DROP TRIGGER TRG_MODIFICAR_INSCRIPCION_JUG;
DROP TRIGGER TRG_ADICIONAR_NOMINA;
DROP TRIGGER TRG_ADICIONAR_INCIDENCIA;
DROP TRIGGER TRG_ELIMINAR_INCIDENCIA;

-- Eliminar Triggers de Auto Incremento
DROP TRIGGER TRG_AI_NOMINA;
DROP TRIGGER TRG_AI_INCIDENCIA;
DROP TRIGGER TRG_AI_RESOLUCION;
DROP TRIGGER TRG_AI_ESTADISTICA_JUGADOR;
DROP TRIGGER TRG_AI_TARIFA;
DROP TRIGGER TRG_AI_FACTURA;
DROP TRIGGER TRG_AI_PAGO;

-- Eliminar Secuencias
DROP SEQUENCE SEQ_NOMINA;
DROP SEQUENCE SEQ_INCIDENCIA;
DROP SEQUENCE SEQ_RESOLUCION;
DROP SEQUENCE SEQ_ESTADISTICA_JUGADOR;
DROP SEQUENCE SEQ_TARIFA;
DROP SEQUENCE SEQ_FACTURA;
DROP SEQUENCE SEQ_PAGO;DROP TRIGGER TRG_MODIFICAR_ESTADISTICA_JUG;
