-- Eliminacion de tablas Ciclo 2

DROP TABLE Pago CASCADE CONSTRAINTS;
DROP TABLE Factura CASCADE CONSTRAINTS;
DROP TABLE Tarifa CASCADE CONSTRAINTS;
DROP TABLE Estadistica_Jugador CASCADE CONSTRAINTS;
DROP TABLE Resolucion CASCADE CONSTRAINTS;
DROP TABLE Incidencia CASCADE CONSTRAINTS;
DROP TABLE Nomina CASCADE CONSTRAINTS;
