-- ========================================================================
-- PAQUETES DE ACTORES (ActoresE) - CICLO 2
-- ========================================================================

-- 1. PA_ORGANIZADOR_C2
CREATE OR REPLACE PACKAGE PA_ORGANIZADOR_C2 IS
    -- De PK_FACTURA
    PROCEDURE AD_TARIFA (xConcepto IN VARCHAR2, xValor IN NUMBER);
    PROCEDURE MOD_TARIFA (xId_Tarifa IN NUMBER, xConcepto IN VARCHAR2, xValor IN NUMBER);
    PROCEDURE EL_TARIFA (xId_Tarifa IN NUMBER);
    PROCEDURE CO_TARIFA (xCursor OUT SYS_REFCURSOR);
    
    PROCEDURE CO_FACTURA (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_PAGO (xCursor OUT SYS_REFCURSOR);
    
    PROCEDURE CO_BALANCE_FINANCIERO (xNombre_Torneo IN VARCHAR2, xTemporada IN VARCHAR2, xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_MOROSOS (xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR);
    
    -- De PK_INCIDENCIA
    PROCEDURE AD_RESOLUCION (xId_Incidencia IN NUMBER, xFechas_Suspension IN NUMBER, xMulta_Monto IN NUMBER, xDescripcion IN VARCHAR2);
    PROCEDURE MOD_RESOLUCION (xId_Resolucion IN NUMBER, xFechas_Suspension IN NUMBER, xMulta_Monto IN NUMBER, xDescripcion IN VARCHAR2);
    PROCEDURE EL_RESOLUCION (xId_Resolucion IN NUMBER);
    PROCEDURE CO_RESOLUCION (xCursor OUT SYS_REFCURSOR);
    
    PROCEDURE CO_HISTORIAL_SANCIONES (xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR);
END PA_ORGANIZADOR_C2;
/

-- 2. PA_REPRESENTANTE_C2
CREATE OR REPLACE PACKAGE PA_REPRESENTANTE_C2 IS
    -- De PK_FACTURA
    PROCEDURE AD_PAGO (xId_Factura IN NUMBER, xId_Representante IN NUMBER, xMonto IN NUMBER);
    PROCEDURE CO_FACTURA (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_PAGO (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_MOROSOS (xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR);
    
    -- De PK_INCIDENCIA
    PROCEDURE CO_HISTORIAL_SANCIONES (xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR);
END PA_REPRESENTANTE_C2;
/

-- 3. PA_TECNICO_C2
CREATE OR REPLACE PACKAGE PA_TECNICO_C2 IS
    -- De PK_NOMINA
    PROCEDURE AD_NOMINA (xId_Partido IN NUMBER, xId_Jugador IN NUMBER, xTitular IN VARCHAR2);
    PROCEDURE MOD_NOMINA (xId_Partido IN NUMBER, xId_Jugador IN NUMBER, xTitular IN VARCHAR2);
    PROCEDURE EL_NOMINA (xId_Partido IN NUMBER, xId_Jugador IN NUMBER);
    PROCEDURE CO_NOMINA (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_PLANTILLA_PARTIDO (xId_Partido IN NUMBER, xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR);
    
    -- De PK_INCIDENCIA
    PROCEDURE CO_LINEA_TIEMPO_PARTIDO (xId_Partido IN NUMBER, xCursor OUT SYS_REFCURSOR);
    
    -- De PK_ESTADISTICA_JUGADOR
    PROCEDURE CO_RANKING_GOLEADORES (xNombre_Torneo IN VARCHAR2, xTemporada IN VARCHAR2, xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_ESTADISTICA_JUGADOR (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_ESTADISTICA_INDIVIDUAL (xId_Jugador IN NUMBER, xCursor OUT SYS_REFCURSOR);
END PA_TECNICO_C2;
/

-- 4. PA_ARBITRO_C2
CREATE OR REPLACE PACKAGE PA_ARBITRO_C2 IS
    -- De PK_INCIDENCIA
    PROCEDURE AD_INCIDENCIA (xId_Partido IN NUMBER, xId_Arbitro IN NUMBER, xId_Jugador IN NUMBER, xMinuto IN NUMBER, xTipo IN VARCHAR2);
    PROCEDURE CO_INCIDENCIA (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_LINEA_TIEMPO_PARTIDO (xId_Partido IN NUMBER, xCursor OUT SYS_REFCURSOR);
    
    -- De PK_NOMINA
    PROCEDURE CO_PLANTILLA_PARTIDO (xId_Partido IN NUMBER, xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR);
END PA_ARBITRO_C2;
/

-- 5. PA_PUBLICO_C2
CREATE OR REPLACE PACKAGE PA_PUBLICO_C2 IS
    -- De PK_INCIDENCIA
    PROCEDURE CO_LINEA_TIEMPO_PARTIDO (xId_Partido IN NUMBER, xCursor OUT SYS_REFCURSOR);
    
    -- De PK_ESTADISTICA_JUGADOR
    PROCEDURE CO_RANKING_GOLEADORES (xNombre_Torneo IN VARCHAR2, xTemporada IN VARCHAR2, xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_ESTADISTICA_JUGADOR (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_ESTADISTICA_INDIVIDUAL (xId_Jugador IN NUMBER, xCursor OUT SYS_REFCURSOR);
    
    -- De PK_NOMINA
    PROCEDURE CO_NOMINA (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_PLANTILLA_PARTIDO (xId_Partido IN NUMBER, xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR);
END PA_PUBLICO_C2;
/

-- 6. PA_ADMINISTRADOR_C2
CREATE OR REPLACE PACKAGE PA_ADMINISTRADOR_C2 IS
    -- Todas las consultas basicas
    PROCEDURE CO_TARIFA (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_FACTURA (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_PAGO (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_NOMINA (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_INCIDENCIA (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_RESOLUCION (xCursor OUT SYS_REFCURSOR);
    PROCEDURE CO_ESTADISTICA_JUGADOR (xCursor OUT SYS_REFCURSOR);
    
    -- Manuales y Bloqueados de PK_FACTURA
    PROCEDURE AD_FACTURA (xId_Inscripcion IN NUMBER, xId_Resolucion IN NUMBER, xId_Tarifa IN NUMBER);
    PROCEDURE MOD_FACTURA (xId_Factura IN NUMBER, xEstado IN VARCHAR2);
    PROCEDURE EL_FACTURA (xId_Factura IN NUMBER);
    PROCEDURE MOD_PAGO (xId_Pago IN NUMBER, xMonto IN NUMBER);
    PROCEDURE EL_PAGO (xId_Pago IN NUMBER);
    
    -- Manuales y Bloqueados de PK_INCIDENCIA
    PROCEDURE MOD_INCIDENCIA (xId_Incidencia IN NUMBER, xMinuto IN NUMBER, xTipo IN VARCHAR2);
    PROCEDURE EL_INCIDENCIA (xId_Incidencia IN NUMBER);
    
    -- Manuales y Bloqueados de PK_ESTADISTICA_JUGADOR
    PROCEDURE AD_ESTADISTICA_JUGADOR (xId_Jugador IN NUMBER, xId_Torneo IN NUMBER);
    PROCEDURE MOD_ESTADISTICA_JUGADOR (xId_Estadistica IN NUMBER, xGoles IN NUMBER, xAsistencias IN NUMBER, xTarjetas_Amarillas IN NUMBER, xTarjetas_Rojas IN NUMBER, xPartidos_Jugados IN NUMBER);
    PROCEDURE EL_ESTADISTICA_JUGADOR (xId_Estadistica IN NUMBER);
END PA_ADMINISTRADOR_C2;
/
