-- ========================================================================
-- PAQUETES DE ACTORES BODY (ActoresI) - CICLO 2
-- ========================================================================

-- 1. PA_ORGANIZADOR_C2
CREATE OR REPLACE PACKAGE BODY PA_ORGANIZADOR_C2 IS
    -- De PK_FACTURA
    PROCEDURE AD_TARIFA (xConcepto IN VARCHAR2, xValor IN NUMBER) IS
    BEGIN PK_FACTURA.AD_TARIFA(xConcepto, xValor); END AD_TARIFA;
    
    PROCEDURE MOD_TARIFA (xId_Tarifa IN NUMBER, xConcepto IN VARCHAR2, xValor IN NUMBER) IS
    BEGIN PK_FACTURA.MOD_TARIFA(xId_Tarifa, xConcepto, xValor); END MOD_TARIFA;
    
    PROCEDURE EL_TARIFA (xId_Tarifa IN NUMBER) IS
    BEGIN PK_FACTURA.EL_TARIFA(xId_Tarifa); END EL_TARIFA;
    
    PROCEDURE CO_TARIFA (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_FACTURA.CO_TARIFA(xCursor); END CO_TARIFA;
    
    PROCEDURE CO_FACTURA (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_FACTURA.CO_FACTURA(xCursor); END CO_FACTURA;
    
    PROCEDURE CO_PAGO (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_FACTURA.CO_PAGO(xCursor); END CO_PAGO;
    
    PROCEDURE CO_BALANCE_FINANCIERO (xNombre_Torneo IN VARCHAR2, xTemporada IN VARCHAR2, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_FACTURA.CO_BALANCE_FINANCIERO(xNombre_Torneo, xTemporada, xCursor); END CO_BALANCE_FINANCIERO;
    
    PROCEDURE CO_MOROSOS (xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_FACTURA.CO_MOROSOS(xNombre_Equipo, xCursor); END CO_MOROSOS;
    
    -- De PK_INCIDENCIA
    PROCEDURE AD_RESOLUCION (xId_Incidencia IN NUMBER, xFechas_Suspension IN NUMBER, xMulta_Monto IN NUMBER, xDescripcion IN VARCHAR2) IS
    BEGIN PK_INCIDENCIA.AD_RESOLUCION(xId_Incidencia, xFechas_Suspension, xMulta_Monto, xDescripcion); END AD_RESOLUCION;
    
    PROCEDURE MOD_RESOLUCION (xId_Resolucion IN NUMBER, xFechas_Suspension IN NUMBER, xMulta_Monto IN NUMBER, xDescripcion IN VARCHAR2) IS
    BEGIN PK_INCIDENCIA.MOD_RESOLUCION(xId_Resolucion, xFechas_Suspension, xMulta_Monto, xDescripcion); END MOD_RESOLUCION;
    
    PROCEDURE EL_RESOLUCION (xId_Resolucion IN NUMBER) IS
    BEGIN PK_INCIDENCIA.EL_RESOLUCION(xId_Resolucion); END EL_RESOLUCION;
    
    PROCEDURE CO_RESOLUCION (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_INCIDENCIA.CO_RESOLUCION(xCursor); END CO_RESOLUCION;
    
    PROCEDURE CO_HISTORIAL_SANCIONES (xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_INCIDENCIA.CO_HISTORIAL_SANCIONES(xNombre_Equipo, xCursor); END CO_HISTORIAL_SANCIONES;
END PA_ORGANIZADOR_C2;
/

-- 2. PA_REPRESENTANTE_C2
CREATE OR REPLACE PACKAGE BODY PA_REPRESENTANTE_C2 IS
    -- De PK_FACTURA
    PROCEDURE AD_PAGO (xId_Factura IN NUMBER, xId_Representante IN NUMBER, xMonto IN NUMBER) IS
    BEGIN PK_FACTURA.AD_PAGO(xId_Factura, xId_Representante, xMonto); END AD_PAGO;
    
    PROCEDURE CO_FACTURA (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_FACTURA.CO_FACTURA(xCursor); END CO_FACTURA;
    
    PROCEDURE CO_PAGO (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_FACTURA.CO_PAGO(xCursor); END CO_PAGO;
    
    PROCEDURE CO_MOROSOS (xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_FACTURA.CO_MOROSOS(xNombre_Equipo, xCursor); END CO_MOROSOS;
    
    -- De PK_INCIDENCIA
    PROCEDURE CO_HISTORIAL_SANCIONES (xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_INCIDENCIA.CO_HISTORIAL_SANCIONES(xNombre_Equipo, xCursor); END CO_HISTORIAL_SANCIONES;
END PA_REPRESENTANTE_C2;
/

-- 3. PA_TECNICO_C2
CREATE OR REPLACE PACKAGE BODY PA_TECNICO_C2 IS
    -- De PK_NOMINA
    PROCEDURE AD_NOMINA (xId_Partido IN NUMBER, xId_Jugador IN NUMBER, xTitular IN VARCHAR2) IS
    BEGIN PK_NOMINA.AD_NOMINA(xId_Partido, xId_Jugador, xTitular); END AD_NOMINA;
    
    PROCEDURE MOD_NOMINA (xId_Partido IN NUMBER, xId_Jugador IN NUMBER, xTitular IN VARCHAR2) IS
    BEGIN PK_NOMINA.MOD_NOMINA(xId_Partido, xId_Jugador, xTitular); END MOD_NOMINA;
    
    PROCEDURE EL_NOMINA (xId_Partido IN NUMBER, xId_Jugador IN NUMBER) IS
    BEGIN PK_NOMINA.EL_NOMINA(xId_Partido, xId_Jugador); END EL_NOMINA;
    
    PROCEDURE CO_NOMINA (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_NOMINA.CO_NOMINA(xCursor); END CO_NOMINA;
    
    PROCEDURE CO_PLANTILLA_PARTIDO (xId_Partido IN NUMBER, xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_NOMINA.CO_PLANTILLA_PARTIDO(xId_Partido, xNombre_Equipo, xCursor); END CO_PLANTILLA_PARTIDO;
    
    -- De PK_INCIDENCIA
    PROCEDURE CO_LINEA_TIEMPO_PARTIDO (xId_Partido IN NUMBER, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_INCIDENCIA.CO_LINEA_TIEMPO_PARTIDO(xId_Partido, xCursor); END CO_LINEA_TIEMPO_PARTIDO;
    
    -- De PK_ESTADISTICA_JUGADOR
    PROCEDURE CO_RANKING_GOLEADORES (xNombre_Torneo IN VARCHAR2, xTemporada IN VARCHAR2, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_ESTADISTICA_JUGADOR.CO_RANKING_GOLEADORES(xNombre_Torneo, xTemporada, xCursor); END CO_RANKING_GOLEADORES;
    
    PROCEDURE CO_ESTADISTICA_JUGADOR (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_ESTADISTICA_JUGADOR.CO_ESTADISTICA_JUGADOR(xCursor); END CO_ESTADISTICA_JUGADOR;
    
    PROCEDURE CO_ESTADISTICA_INDIVIDUAL (xId_Jugador IN NUMBER, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_ESTADISTICA_JUGADOR.CO_ESTADISTICA_INDIVIDUAL(xId_Jugador, xCursor); END CO_ESTADISTICA_INDIVIDUAL;
END PA_TECNICO_C2;
/

-- 4. PA_ARBITRO_C2
CREATE OR REPLACE PACKAGE BODY PA_ARBITRO_C2 IS
    -- De PK_INCIDENCIA
    PROCEDURE AD_INCIDENCIA (xId_Partido IN NUMBER, xId_Arbitro IN NUMBER, xId_Jugador IN NUMBER, xMinuto IN NUMBER, xTipo IN VARCHAR2) IS
    BEGIN PK_INCIDENCIA.AD_INCIDENCIA(xId_Partido, xId_Arbitro, xId_Jugador, xMinuto, xTipo); END AD_INCIDENCIA;
    
    PROCEDURE CO_INCIDENCIA (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_INCIDENCIA.CO_INCIDENCIA(xCursor); END CO_INCIDENCIA;
    
    PROCEDURE CO_LINEA_TIEMPO_PARTIDO (xId_Partido IN NUMBER, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_INCIDENCIA.CO_LINEA_TIEMPO_PARTIDO(xId_Partido, xCursor); END CO_LINEA_TIEMPO_PARTIDO;
    
    -- De PK_NOMINA
    PROCEDURE CO_PLANTILLA_PARTIDO (xId_Partido IN NUMBER, xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_NOMINA.CO_PLANTILLA_PARTIDO(xId_Partido, xNombre_Equipo, xCursor); END CO_PLANTILLA_PARTIDO;
END PA_ARBITRO_C2;
/

-- 5. PA_PUBLICO_C2
CREATE OR REPLACE PACKAGE BODY PA_PUBLICO_C2 IS
    -- De PK_INCIDENCIA
    PROCEDURE CO_LINEA_TIEMPO_PARTIDO (xId_Partido IN NUMBER, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_INCIDENCIA.CO_LINEA_TIEMPO_PARTIDO(xId_Partido, xCursor); END CO_LINEA_TIEMPO_PARTIDO;
    
    -- De PK_ESTADISTICA_JUGADOR
    PROCEDURE CO_RANKING_GOLEADORES (xNombre_Torneo IN VARCHAR2, xTemporada IN VARCHAR2, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_ESTADISTICA_JUGADOR.CO_RANKING_GOLEADORES(xNombre_Torneo, xTemporada, xCursor); END CO_RANKING_GOLEADORES;
    
    PROCEDURE CO_ESTADISTICA_JUGADOR (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_ESTADISTICA_JUGADOR.CO_ESTADISTICA_JUGADOR(xCursor); END CO_ESTADISTICA_JUGADOR;
    
    PROCEDURE CO_ESTADISTICA_INDIVIDUAL (xId_Jugador IN NUMBER, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_ESTADISTICA_JUGADOR.CO_ESTADISTICA_INDIVIDUAL(xId_Jugador, xCursor); END CO_ESTADISTICA_INDIVIDUAL;
    
    -- De PK_NOMINA
    PROCEDURE CO_NOMINA (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_NOMINA.CO_NOMINA(xCursor); END CO_NOMINA;
    
    PROCEDURE CO_PLANTILLA_PARTIDO (xId_Partido IN NUMBER, xNombre_Equipo IN VARCHAR2, xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_NOMINA.CO_PLANTILLA_PARTIDO(xId_Partido, xNombre_Equipo, xCursor); END CO_PLANTILLA_PARTIDO;
END PA_PUBLICO_C2;
/

-- 6. PA_ADMINISTRADOR_C2
CREATE OR REPLACE PACKAGE BODY PA_ADMINISTRADOR_C2 IS
    -- Todas las consultas basicas
    PROCEDURE CO_TARIFA (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_FACTURA.CO_TARIFA(xCursor); END CO_TARIFA;
    
    PROCEDURE CO_FACTURA (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_FACTURA.CO_FACTURA(xCursor); END CO_FACTURA;
    
    PROCEDURE CO_PAGO (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_FACTURA.CO_PAGO(xCursor); END CO_PAGO;
    
    PROCEDURE CO_NOMINA (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_NOMINA.CO_NOMINA(xCursor); END CO_NOMINA;
    
    PROCEDURE CO_INCIDENCIA (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_INCIDENCIA.CO_INCIDENCIA(xCursor); END CO_INCIDENCIA;
    
    PROCEDURE CO_RESOLUCION (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_INCIDENCIA.CO_RESOLUCION(xCursor); END CO_RESOLUCION;
    
    PROCEDURE CO_ESTADISTICA_JUGADOR (xCursor OUT SYS_REFCURSOR) IS
    BEGIN PK_ESTADISTICA_JUGADOR.CO_ESTADISTICA_JUGADOR(xCursor); END CO_ESTADISTICA_JUGADOR;
    
    -- Manuales y Bloqueados de PK_FACTURA
    PROCEDURE AD_FACTURA (xId_Inscripcion IN NUMBER, xId_Resolucion IN NUMBER, xId_Tarifa IN NUMBER) IS
    BEGIN PK_FACTURA.AD_FACTURA(xId_Inscripcion, xId_Resolucion, xId_Tarifa); END AD_FACTURA;
    
    PROCEDURE MOD_FACTURA (xId_Factura IN NUMBER, xEstado IN VARCHAR2) IS
    BEGIN PK_FACTURA.MOD_FACTURA(xId_Factura, xEstado); END MOD_FACTURA;
    
    PROCEDURE EL_FACTURA (xId_Factura IN NUMBER) IS
    BEGIN PK_FACTURA.EL_FACTURA(xId_Factura); END EL_FACTURA;
    
    PROCEDURE MOD_PAGO (xId_Pago IN NUMBER, xMonto IN NUMBER) IS
    BEGIN PK_FACTURA.MOD_PAGO(xId_Pago, xMonto); END MOD_PAGO;
    
    PROCEDURE EL_PAGO (xId_Pago IN NUMBER) IS
    BEGIN PK_FACTURA.EL_PAGO(xId_Pago); END EL_PAGO;
    
    -- Manuales y Bloqueados de PK_INCIDENCIA
    PROCEDURE MOD_INCIDENCIA (xId_Incidencia IN NUMBER, xMinuto IN NUMBER, xTipo IN VARCHAR2) IS
    BEGIN PK_INCIDENCIA.MOD_INCIDENCIA(xId_Incidencia, xMinuto, xTipo); END MOD_INCIDENCIA;
    
    PROCEDURE EL_INCIDENCIA (xId_Incidencia IN NUMBER) IS
    BEGIN PK_INCIDENCIA.EL_INCIDENCIA(xId_Incidencia); END EL_INCIDENCIA;
    
    -- Manuales y Bloqueados de PK_ESTADISTICA_JUGADOR
    PROCEDURE AD_ESTADISTICA_JUGADOR (xId_Jugador IN NUMBER, xId_Torneo IN NUMBER) IS
    BEGIN PK_ESTADISTICA_JUGADOR.AD_ESTADISTICA_JUGADOR(xId_Jugador, xId_Torneo); END AD_ESTADISTICA_JUGADOR;
    
    PROCEDURE MOD_ESTADISTICA_JUGADOR (xId_Estadistica IN NUMBER, xGoles IN NUMBER, xAsistencias IN NUMBER, xTarjetas_Amarillas IN NUMBER, xTarjetas_Rojas IN NUMBER, xPartidos_Jugados IN NUMBER) IS
    BEGIN PK_ESTADISTICA_JUGADOR.MOD_ESTADISTICA_JUGADOR(xId_Estadistica, xGoles, xAsistencias, xTarjetas_Amarillas, xTarjetas_Rojas, xPartidos_Jugados); END MOD_ESTADISTICA_JUGADOR;
    
    PROCEDURE EL_ESTADISTICA_JUGADOR (xId_Estadistica IN NUMBER) IS
    BEGIN PK_ESTADISTICA_JUGADOR.EL_ESTADISTICA_JUGADOR(xId_Estadistica); END EL_ESTADISTICA_JUGADOR;
END PA_ADMINISTRADOR_C2;
/
