-- ========================================================================
-- LIMPIEZA DE SEGURIDAD (Drop Roles) - CICLO 2
-- ========================================================================

-- 1. Revocacion de permisos (REVOKE) por buena practica
REVOKE EXECUTE ON PA_ADMINISTRADOR_C2 FROM RL_ADMINISTRADOR;
REVOKE EXECUTE ON PA_ORGANIZADOR_C2 FROM RL_ORGANIZADOR;
REVOKE EXECUTE ON PA_REPRESENTANTE_C2 FROM RL_REPRESENTANTE;
REVOKE EXECUTE ON PA_TECNICO_C2 FROM RL_TECNICO;
REVOKE EXECUTE ON PA_ARBITRO_C2 FROM RL_ARBITRO;
REVOKE EXECUTE ON PA_PUBLICO_C2 FROM RL_PUBLICO;

-- 2. Eliminar los roles oficiales de la base de datos
DROP ROLE RL_ADMINISTRADOR;
DROP ROLE RL_ORGANIZADOR;
DROP ROLE RL_REPRESENTANTE;
DROP ROLE RL_TECNICO;
DROP ROLE RL_ARBITRO;
DROP ROLE RL_PUBLICO;

-- 3. Eliminar paquetes de actores (Fachadas)
DROP PACKAGE PA_ADMINISTRADOR_C2;
DROP PACKAGE PA_ORGANIZADOR_C2;
DROP PACKAGE PA_REPRESENTANTE_C2;
DROP PACKAGE PA_TECNICO_C2;
DROP PACKAGE PA_ARBITRO_C2;
DROP PACKAGE PA_PUBLICO_C2;
