-- 10_XDisparadores.sql

-- 1. Personas y Roles
DROP TRIGGER TRG_MANTENER_PERSONA;
DROP TRIGGER TRG_ADICIONAR_JUGADOR;
DROP TRIGGER TRG_ELIMINAR_JUGADOR;
DROP TRIGGER TRG_ADICIONAR_TECNICO;
DROP TRIGGER TRG_MODIFICAR_TECNICO;
DROP TRIGGER TRG_ELIMINAR_TECNICO;
DROP TRIGGER TRG_ADICIONAR_ARBITRO;
DROP TRIGGER TRG_ELIMINAR_ARBITRO;
DROP TRIGGER TRG_ADICIONAR_ORGANIZADOR;
DROP TRIGGER TRG_ELIMINAR_ORGANIZADOR;
DROP TRIGGER TRG_ADICIONAR_REPRESENTANTE;
DROP TRIGGER TRG_ELIMINAR_REPRESENTANTE;

-- 2. Inscripciones
DROP TRIGGER TRG_ADICIONAR_INSCRIPCION;
DROP TRIGGER TRG_MODIFICAR_INSCRIPCION;
DROP TRIGGER TRG_ELIMINAR_INSCRIPCION;
DROP TRIGGER TRG_ADICIONAR_ESTADISITICA_EQUIPO; 

DROP TRIGGER TRG_MODIFICAR_EQUIPO;
DROP TRIGGER TRG_ELIMINAR_EQUIPO;
DROP TRIGGER TRG_EQUIPO_VALIDAR_FECHA;
DROP TRIGGER TRG_MODIFICAR_PATROCINADOR;
DROP TRIGGER TRG_ELIMINAR_PATROCINADOR;
DROP TRIGGER TRG_ELIMINAR_ESTADIO;

-- 4. Fases
DROP TRIGGER TRG_ADICIONAR_FASE;
DROP TRIGGER TRG_MODIFICAR_FASE;
DROP TRIGGER TRG_ELIMINAR_FASE;

-- 5. Partidos
DROP TRIGGER TRG_INSERTAR_PARTIDO;
DROP TRIGGER TRG_MODIFICAR_PARTIDO;
DROP TRIGGER TRG_MODIFICAR_ESTADISTICA_EQUIPO_PARTIDO; 
DROP TRIGGER TRG_ELIMINAR_PARTIDO;

-- 6. Estadisticas
DROP TRIGGER TRG_MODIFICAR_ESTADISTICA_EQUIPO;
DROP TRIGGER TRG_ELIMINAR_ESTADISTICA_EQUIPO;

-- 7. Torneo
DROP TRIGGER TRG_INSERTAR_TORNEO;
DROP TRIGGER TRG_MODIFICAR_TORNEO;
DROP TRIGGER TRG_ELIMINAR_TORNEO;

-- 8. Auto Increment
DROP SEQUENCE SEQ_PERSONA;
DROP SEQUENCE SEQ_EQUIPO;
DROP SEQUENCE SEQ_TORNEO;
DROP SEQUENCE SEQ_ESTADIO;
DROP SEQUENCE SEQ_PATROCINADOR;
DROP SEQUENCE SEQ_INSCRIPCION;
DROP SEQUENCE SEQ_PARTIDO;
DROP SEQUENCE SEQ_ESTADISTICA_EQUIPO;

DROP TRIGGER TRG_AI_PERSONA;
DROP TRIGGER TRG_AI_EQUIPO;
DROP TRIGGER TRG_AI_TORNEO;
DROP TRIGGER TRG_AI_ESTADIO;
DROP TRIGGER TRG_AI_PATROCINADOR;
DROP TRIGGER TRG_AI_INSCRIPCION;
DROP TRIGGER TRG_AI_PARTIDO;
DROP TRIGGER TRG_AI_ESTADISTICA_EQUIPO;
