-- xCRUD Eliminacion de Paquetes

DROP PACKAGE PK_PERSONA;
DROP PACKAGE PK_EQUIPO;
DROP PACKAGE PK_TORNEO;
DROP PACKAGE PK_INSCRIPCION;
DROP PACKAGE PK_PARTIDO;
DROP PACKAGE PK_ESTADISTICA_EQUIPO;
DROP PACKAGE PK_ESTADIO;
DROP PACKAGE PK_PATROCINADOR;