
-- Creación de Roles
CREATE ROLE RL_ADMINISTRADOR;
CREATE ROLE RL_ORGANIZADOR;
CREATE ROLE RL_REPRESENTANTE;
CREATE ROLE RL_TECNICO;
CREATE ROLE RL_ARBITRO;
CREATE ROLE RL_PUBLICO;

-- Asignación de Permisos
GRANT EXECUTE ON PA_ADMINISTRADOR_SISTEMA TO RL_ADMINISTRADOR;
GRANT EXECUTE ON PA_ORGANIZADOR_TORNEO TO RL_ORGANIZADOR;
GRANT EXECUTE ON PA_REPRESENTANTE_EQUIPO TO RL_REPRESENTANTE;
GRANT EXECUTE ON PA_TECNICO TO RL_TECNICO;
GRANT EXECUTE ON PA_ARBITRO TO RL_ARBITRO;
GRANT EXECUTE ON PA_PUBLICO_GENERAL TO RL_PUBLICO;
