-- XSeguridad - Eliminación de paquetes de actores, roles y permisos

-- Revocar permisos
REVOKE EXECUTE ON PA_ADMINISTRADOR_SISTEMA FROM RL_ADMINISTRADOR;
REVOKE EXECUTE ON PA_ORGANIZADOR_TORNEO FROM RL_ORGANIZADOR;
REVOKE EXECUTE ON PA_REPRESENTANTE_EQUIPO FROM RL_REPRESENTANTE;
REVOKE EXECUTE ON PA_TECNICO FROM RL_TECNICO;
REVOKE EXECUTE ON PA_ARBITRO FROM RL_ARBITRO;
REVOKE EXECUTE ON PA_PUBLICO_GENERAL FROM RL_PUBLICO;

-- Eliminar roles
DROP ROLE RL_ADMINISTRADOR;
DROP ROLE RL_ORGANIZADOR;
DROP ROLE RL_REPRESENTANTE;
DROP ROLE RL_TECNICO;
DROP ROLE RL_ARBITRO;
DROP ROLE RL_PUBLICO;

-- Eliminar paquetes de actores
DROP PACKAGE PA_ADMINISTRADOR_SISTEMA;
DROP PACKAGE PA_ORGANIZADOR_TORNEO;
DROP PACKAGE PA_REPRESENTANTE_EQUIPO;
DROP PACKAGE PA_TECNICO;
DROP PACKAGE PA_ARBITRO;
DROP PACKAGE PA_PUBLICO_GENERAL;
